Repository 42-TRANSENDENCE/backend, pull requests merged in 2023-03, with the labels that each got.

#25 feat: 회원가입 기능 #24
  package-lock.json
  package.json
  src/app.module.ts
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/auth/strategies/fourty-two.strategy.ts
  src/main.ts
  src/users/dto/createUserDto.ts
  src/users/dto/users.dto.ts
  src/users/users.controller.ts
  src/users/users.entity.ts
  src/users/users.module.ts
  src/users/users.service.ts
Labels: documentation, enhancement

#29 fix: 환경변수 이름 수정
  src/database/database.module.ts
Labels: bug

#30 refactor: 회원 가입 기능 리팩토링
  src/users/dto/users.dto.ts
  src/users/users.controller.ts
  src/users/users.service.ts
Labels: enhancement

#32 feat: Swagger API 문서화
  src/auth/auth.controller.ts
  src/auth/auth.service.ts
  src/auth/two-factor-authentication/two-factor-auth.controller.ts
  src/auth/two-factor-authentication/two-factor-token.dto.ts
  src/auth/two-factor-authentication/two-factor-token.interface.ts
  src/main.ts
  src/users/users.controller.ts
  src/users/users.entity.ts
Labels: documentation, enhancement

#35 Feat/token dto validation
  src/auth/auth.controller.ts
  src/auth/auth.service.ts
  src/auth/two-factor-authentication/two-factor-auth.controller.ts
  src/auth/two-factor-authentication/two-factor-token.dto.ts
Labels: bug, enhancement

#28 Feat/chat
  package-lock.json
  package.json
  src/app.module.ts
  src/channels/channelcember.entity.ts
  src/channels/channels.controller.spec.ts
  src/channels/channels.controller.ts
  src/channels/channels.entity.ts
  src/channels/channels.module.ts
  src/channels/channels.service.spec.ts
  src/channels/channels.service.ts
  src/channels/dto/create-channel.dto.ts
  src/chats/chats.controller.spec.ts
  src/chats/chats.controller.ts
  src/chats/chats.entity.ts
  src/chats/chats.module.ts
  src/chats/chats.service.spec.ts
  src/chats/chats.service.ts
  src/common/decorators/user.decorator.ts
  src/events/events.channels.gateway.ts
  src/events/events.chat.gateway.ts
  src/events/events.module.ts
  src/users/users.entity.ts
Labels: enhancement

#38 Test/auth
  src/auth/auth.controller.spec.ts
  src/auth/auth.service.spec.ts
  src/auth/auth.service.ts
  src/users/users.controller.ts
  src/utils/mocks/config.service.ts
  src/utils/mocks/jwt.service.ts
Labels: bug, refactoring, test

#40 feat: Log 기능 추가
  src/auth/strategies/jwt-refresh.strategy.ts
  src/auth/strategies/jwt-two-factor.strategy.ts
  src/auth/two-factor-authentication/two-factor-auth.service.ts
  src/users/users.service.ts
Labels: enhancement

#41 feat: Login Queue 구현
  package-lock.json
  package.json
  src/app.module.ts
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/login.consumer.ts
  src/auth/strategies/fourty-two.strategy.ts
Labels: enhancement

#46 feat: 로그인 issue 해결 #45
  package.json
  src/app.module.ts
  src/auth/auth.constants.ts
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/auth/guards/auth-session.guard.ts
  src/auth/guards/fourty-two.guard.ts
  src/auth/interface/fourty-two-token.interface.ts
  src/auth/interface/request-with-session.interface.ts
  src/auth/interface/session-payload.interface.ts
  src/auth/interface/token-payload.interface.ts
  src/auth/login.consumer.ts
  src/auth/strategies/fourty-two.strategy.ts
  src/auth/strategies/jwt-refresh.strategy.ts
  src/auth/strategies/jwt-two-factor.strategy.ts
  src/auth/strategies/jwt.strategy.ts
  src/main.ts
  src/users/users.controller.ts
  src/users/users.service.ts
Labels: bug, enhancement

#47 refactor: Auth module refactoring
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/auth/decorator/session-info.decorator.ts
  src/auth/decorator/token.decorator.ts
  src/auth/decorator/user.decorator.ts
  src/auth/guards/auth-session.guard.ts
  src/auth/guards/fourty-two.guard.ts
  src/auth/interface/fourty-two-token.interface.ts
  src/auth/interface/jwt-token-payload.interface.ts
  src/auth/interface/request-with-session.interface.ts
  src/auth/login.consumer.ts
  src/auth/strategies/jwt-refresh.strategy.ts
  src/auth/strategies/jwt-two-factor.strategy.ts
  src/auth/strategies/jwt.strategy.ts
  src/auth/two-factor-authentication/two-factor-auth.controller.ts
  src/users/users.service.ts
Labels: refactoring

#51 refactor: auth refactoring
  package-lock.json
  src/auth/auth.constants.ts
  src/auth/auth.controller.ts
  src/auth/auth.service.ts
  src/auth/guards/fourty-two.guard.ts
  src/auth/login.consumer.ts
  src/auth/queue/login.consumer.ts
  src/auth/two-factor-authentication/two-factor-auth.service.ts
  src/users/users.service.ts
Labels: refactoring

#52 fix: compile error
  src/auth/two-factor-authentication/two-factor-auth.controller.ts
Labels: bug

#55 Test/auth
  src/auth/auth.controller.spec.ts
  src/auth/auth.module.ts
  src/auth/auth.service.spec.ts
  src/auth/test/auth.controller.spec.ts
  src/auth/test/auth.service.spec.ts
  src/auth/test/two-factor-auth.service.spec.ts
  src/utils/mocks/config.service.ts
Labels: test

#56 Fix/2 fa
  src/auth/two-factor-authentication/two-factor-auth.controller.ts
  src/auth/two-factor-authentication/two-factor-auth.service.ts
Labels: bug

#66 feat: nickname 검증 기능 추가
  src/users/dto/users.dto.ts
Labels: enhancement

#68 Feat/friends
  .dockerignore
  Dockerfile
  package.json
  src/auth/test/auth.controller.spec.ts
  src/auth/test/two-factor-auth.service.spec.ts
  src/main.ts
  src/users/friends/friends.controller.spec.ts
  src/users/friends/friends.controller.ts
  src/users/friends/friends.service.spec.ts
  src/users/friends/friends.service.ts
  src/users/friends/friendship.entity.ts
  src/users/users.constants.ts
  src/users/users.controller.ts
  src/users/users.entity.ts
  src/users/users.module.ts
  src/users/users.service.ts
Labels: enhancement

#77 Feat/cicd
  .github/workflow/nest-ci.yml
  .github/workflows/nest-ci.yml
  src/channels/channels.controller.spec.ts
  src/channels/channels.service.spec.ts
  src/chats/chats.controller.spec.ts
  src/chats/chats.service.spec.ts
Labels: enhancement

#79 fix: package.json 최신화
  .github/workflows/nest-ci.yml
  package-lock.json
  package.json
Labels: bug

#88 Feat/users
  package-lock.json
  src/users/dto/users.dto.ts
  src/users/users.controller.ts
  src/users/users.service.ts
Labels: enhancement

#90 Fix/api
  src/game/game.controller.ts
  src/game/ingame.service.ts
  src/game/waiting.service.ts
  src/users/users.controller.ts
Labels: bug

#92 fix: npm ci 문제 해결
  .github/workflows/nest-ci.yml
Labels: bug

#91 Feat/42 api
  package-lock.json
  package.json
  src/app.module.ts
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/auth/decorator/code.decorator.ts
  src/auth/guards/fourty-two.guard.ts
  src/auth/login.service.ts
  src/auth/queue/login.consumer.ts
  src/auth/test/auth.controller.spec.ts
  src/auth/test/auth.service.spec.ts
Labels: enhancement

#95 Refactor/users
  src/auth/auth.controller.ts
  src/auth/login.service.ts
  src/auth/strategies/jwt-refresh.strategy.ts
  src/auth/test/auth.controller.spec.ts
  src/auth/test/auth.service.spec.ts
  src/users/friends/friends.constants.ts
  src/users/friends/friends.controller.ts
  src/users/friends/friends.service.spec.ts
  src/users/friends/friends.service.ts
  src/users/users.constants.ts
  src/users/users.controller.ts
  src/users/users.entity.ts
  src/users/users.service.ts
Labels: refactoring

#97 Cherry/chat/password hash
  package-lock.json
  package.json
  src/app.module.ts
  src/channels/channelcember.entity.ts
  src/channels/channels.controller.ts
  src/channels/channels.entity.ts
  src/channels/channels.module.ts
  src/channels/channels.service.ts
  src/channels/dto/create-channel.dto.ts
  src/chats/chats.controller.ts
  src/chats/chats.entity.ts
  src/chats/chats.module.ts
  src/chats/chats.service.ts
  src/chats/dto/chats.dto.ts
  src/common/decorators/user.decorator.ts
  src/events/events.channels.gateway.ts
  src/events/events.chat.gateway.ts
  src/events/events.module.ts
  src/game/game.gateway.ts
  src/game/game.interface.ts
  src/game/game.module.ts
  src/game/game.service.ts
  src/game/lobby.service.ts
Labels: enhancement

#98 fix: CD 버그 수정
  .github/workflows/nest-ci.yml
Labels: bug

#100 Feat/auth
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/auth/interface/user-status.enum.ts
  src/auth/test/auth.service.spec.ts
  src/users/friends/friendship.entity.ts
Labels: enhancement

#101 Feat/game
  src/game/game.constants.ts
  src/game/game.gateway.ts
  src/game/game.interface.ts
  src/game/game.module.ts
  src/game/game.service.ts
  src/game/history/history.entity.ts
  src/game/history/history.service.ts
  src/game/lobby.service.ts
  src/game/lobby/lobby.interface.ts
  src/game/lobby/lobby.service.ts
  src/game/player/player.interface.ts
  src/game/player/player.service.ts
  src/game/queue/queue.service.ts
  src/users/friends/friends.service.ts
  src/users/users.entity.ts
Labels: enhancement, refactoring

#102 Feat/chat/socket
  src/channels/channel.interface.ts
  src/channels/channels.controller.ts
  src/channels/channels.module.ts
  src/channels/channels.service.ts
  src/chats/chats.controller.ts
  src/chats/chats.service.ts
  src/events/events.channels.gateway.ts
Labels: enhancement

#106 Feat/chat/db
  .github/workflows/nest-ci.yml
  src/auth/test/auth.controller.spec.ts
  src/channels/channelmember.entity.ts
  src/channels/channels.controller.ts
  src/channels/channels.entity.ts
  src/channels/channels.module.ts
  src/channels/channels.service.ts
  src/chats/chats.controller.ts
  src/chats/chats.entity.ts
  src/chats/chats.module.ts
  src/chats/chats.service.ts
  src/events/ dto/leave.dto.ts
  src/events/events.channels.gateway.ts
  src/events/events.module.ts
  src/users/friends/friends.service.spec.ts
  src/users/users.entity.ts
Labels: enhancement
